language: java

addons:
  sonarcloud:
    organization: "wingelo-github"

sudo: true

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=ex_eval_350